# S09 Numpy

Mit Patel. Version: 1.00 (August 2023).

***

# 9. Python for scientific calculation: the NumPy module

Numerical Python ([NumPy](http://www.numpy.org/)) is a key Python package for high-performance numerical computation and data analysis. It is the foundation on which most scientific tools written in Python are based.

It contains, among others:

- The `ndarray`: type of multidimensional variable (_object_) (called _array_, from English)
- _Vectorized_ mathematical functions to quickly perform standard mathematical operations on entire data collections without having to type loops
- Tools for reading / writing data to disk and working with files
- Linear algebra tools, random number generation, and Fourier transform
- Tools for the integration of written codes in other programming languages ​​such as C, C ++ and Fortran

An _ndarray_ (or _numpy array_ or _NumPy array_) is a collection (vector, array, tensor) of data:

- all of the same type and,
- of fixed size since its creation.

Remember that _lists_, on the other hand, allow you to combine different types of data and can vary in length.

But these limitations allow to define many operations on the _ndarray_ and that these operations are well optimized (they are done very quickly) which has its importance in long programs.


## 9.1 A simple example

Until now, if we wanted to calculate the value of the sines of a whole list of angles in radians, we could do so for example (check it in the following cell):
```Python
import math
angles = [0, math.pi / 4, math.pi / 2, 3 * math.pi / 4, math.pi] # List of angles in radians
sin_ang = [] # An empty sine list is created
for ang in angles: # For each angle in the list
    res = math.sin (ang) # The sine is calculated
    sin_ang.append (nothing) # Added to the sine list
print ("Angles: {}". format (angles))
print ("Sinus: {}". format (sin_ang))
```

In [ ]:
import math
angles = [0, math.pi / 4, math.pi / 2, 3 * math.pi / 4, math.pi] # List of angles in radians
sin_ang = [] # An empty sine list is created
for ang in angles: # For each angle in the list
    res = math.sin (ang) # The sine is calculated
    sin_ang.append (res) # Added to the sine list
print ("Angles: {}". format (angles))
print ("Sinus: {}". format (sin_ang))

Angles: [0, 0.7853981633974483, 1.5707963267948966, 2.356194490192345, 3.141592653589793]
Sinus: [0.0, 0.7071067811865475, 1.0, 0.7071067811865476, 1.2246467991473532e-16]


This way of working can be very inefficient numerically if the list has many elements (thousands or millions).

A much more efficient, and easier way to encode, is to use the `numpy` module.

```Python
import numpy
angles = [0, numpy.pi / 4, numpy.pi / 2, 3 * numpy.pi / 4, numpy.pi] # List of angles in radians
angles = numpy.array (angles) # The list is transformed into a numpy array
sin_ang = numpy.sin (angles) # The sine of all angles is calculated with a single instruction
print ("Angles: {}". format (angles))
print ("Sinus: {}". format (sin_ang))
```

Run this program in the next cell and check that the numeric values are the same.

In [ ]:
import numpy
angles = [0, numpy.pi / 4, numpy.pi / 2, 3 * numpy.pi / 4, numpy.pi] # List of angles in radians
angles = numpy.array (angles) # The list is transformed into a numpy array
sin_ang = numpy.sin (angles) # The sine of all angles is calculated with a single instruction
print ("Angles: {}". format (angles))
print ("Sinus: {}". format (sin_ang))

Angles: [0.         0.78539816 1.57079633 2.35619449 3.14159265]
Sinus: [0.00000000e+00 7.07106781e-01 1.00000000e+00 7.07106781e-01
 1.22464680e-16]


Note that the numpy module includes the `pi` number and the` sinus` function, so it is not necessary to use the `math` module here.

After the `numpy.array` statement the variable _angles_ is no longer of type` list` and is a _numpy array_. This can be seen by typing its type using the `type () ` function that can be used whenever you want to check the type of a variable.

Run this code snippet in the following cell to check:
```Python
import numpy
angles = [0, numpy.pi / 4, numpy.pi / 2, 3 * numpy.pi / 4, numpy.pi]
print ("Before the numpy.array statement the type of the angle variable is:", type (angles))
angles = numpy.array (angles)
print ("After the numpy.array statement the angle variable type is:", type (angles))
```

In [ ]:
import numpy
angles = [0, numpy.pi / 4, numpy.pi / 2, 3 * numpy.pi / 4, numpy.pi]
print ("Before the numpy.array statement the type of the angle variable is:", type (angles))
angles = numpy.array (angles)
print ("After the numpy.array statement the angle variable type is:", type (angles))

Before the numpy.array statement the type of the angle variable is: <class 'list'>
After the numpy.array statement the angle variable type is: <class 'numpy.ndarray'>


If for some reason you want to keep the list of angles as _list_ you could do this for example:
```Python
import numpy
angles = [0, numpy.pi / 4, numpy.pi / 2, 3 * numpy.pi / 4, numpy.pi] # List of angles in radians
a_angles = numpy.array (angles) # Transforms the list into a numpy array and assigns it to a new variable
sin_ang = numpy.sin (a_angles) # Calculates the sine of all angles with a single statement
print ("List of angles: {}". format (angles))
print ("Angle array: {}". format (a_angles))
print ("Sinus Array: {}". format (sin_ang))
```

In [ ]:
import numpy
angles = [0, numpy.pi / 4, numpy.pi / 2, 3 * numpy.pi / 4, numpy.pi] # List of angles in radians
a_angles = numpy.array (angles) # Transforms the list into a numpy array and assigns it to a new variable
sin_ang = numpy.sin (a_angles) # Calculates the sine of all angles with a single statement
print ("List of angles: {}". format (angles))
print ("Angle array: {}". format (a_angles))
print ("Sinus Array: {}". format (sin_ang))

List of angles: [0, 0.7853981633974483, 1.5707963267948966, 2.356194490192345, 3.141592653589793]
Angle array: [0.         0.78539816 1.57079633 2.35619449 3.14159265]
Sinus Array: [0.00000000e+00 7.07106781e-01 1.00000000e+00 7.07106781e-01
 1.22464680e-16]


## 9.2 Indexed variables: NumPy _ndarray_

In a _ndarray_ we don't necessarily have to store numeric values, they can contain any value, but unlike lists, arrays are **homogeneous**, that is, all their elements must be of the same type. We will, however, basically work with arrays where their elements will be numeric values.

In addition, each array has a shape or shape. For now we will focus on arrays (collections) **one-dimensional**. A one-dimensional or 1-dimensional array is what in mathematics we would call a `vector` and to obtain the value of one of its elements it is necessary to indicate the name of the variable and specify a single index.

We will first look at how to construct these vectors and then use them.

## 9.3 NumPy vectors

### 9.3.1 Creating one-dimensional arrays (vectors)

In this section we will see how a NumPy array can be generated. Although there are many ways, we will focus on creating _arrays_:

- from a list.
- using NumPy functions for creating arrays.
- applying NumPy functions on pre-existing arrays.
- using data entered by the user.

#### Create a NumPy vector from a list

We've seen an example before with converting a list of angles to a _numpy array_.

Now we can see a couple more in the following code:
```Python
import numpy as np # This will put np instead of numpy
smooth1 = [1, 2.5, 3, 4.5, 5] # List with integer and actual data
arr1 = np.array (smooth1) # Converts the list to a numpy array
print (arr1)
smooth2 = [1.5, 1d + 2, 2.5, 3, 3.5] # List with integer, real, and complex data
arr2 = np.array (smooth2) # The list is converted to a numpy array
print (arr2)
```
Check it out.


In [ ]:
import numpy as np # This will put np instead of numpy
smooth1 = [1, 2.5, 3, 4.5, 5] # List with integer and actual data
arr1 = np.array (smooth1) # Converts the list to a numpy array
print (arr1)
smooth2 = [1.5, 1j + 2, 2.5, 3, 3.5] # List with integer, real, and complex data
arr2 = np.array (smooth2) # The list is converted to a numpy array
print (arr2)

[1.  2.5 3.  4.5 5. ]
[1.5+0.j 2. +1.j 2.5+0.j 3. +0.j 3.5+0.j]


Note that if we use a list of numeric values of different types, NumPy creates the array with the most general type (real in the first case of the example and complex in the second case).

#### Create a NumPy vector from scratch

If we want to create a NumPy vector from scratch, without doing so from a previous list or array, we have a number of functions in the NumPy module that make it possible:

**`numpy.linspace ()` function:**

- The function `numpy.linspace ()` creates an array with **real** values (`float`) equally spaced between an initial and a final value.

The following is an example where the result of the function is assigned to a variable "` x` ":

> ```python
x = numpy.linspace (start, stop, num)
```

The function has **required arguments**:

- `start`: initial value of the sequence (real number)
- `stop`: final value of the sequence (real number)

and an **optional argument**:

- `num`: number of values that the array must contain (integer value). If no value is specified, the function defaults to 50 values.

Here is an example where we generate an array of 21 values equally spaced between -2.0 and 2.0:
```Python
import numpy
npunts = 21
values = numpy.linspace (-2.0, 2.0, npoints)
print (values)
```

Check how it works:

In [ ]:
import numpy
npoints = 21
values = numpy.linspace (-2.0, 2.0,5)
print (values)

[-2. -1.  0.  1.  2.]


**`numpy.arange ()` function:**

- The `numpy.arange ()` function behaves similarly to `range ()` in standard Python. In this case, the NumPy function generates a NumPy vector that contains a sequence of integers between the `start` value and a` stop` value (not included!) In increments of `step`. The following is an example where the result of the function is assigned to a variable "` x` ":

```python
x = numpy.arange (start, stop, step)
```

Of the three function arguments, only `stop` is required. For optional arguments:

   - `start`: we can specify the initial value of the sequence (default` start = 0`).
   - `step`: we can specify the increment between consecutive values ​​of the sequence (default` step = 1`)
    
It is important to remember that, as in Python's `range ()` function, **the value of `stop` is excluded from the sequence**.

The following code uses the arange () function to construct a NumPy array that contains the integer sequence 0, 1, 2, ..., 8:
```Python
import numpy
vect = numpy.arange (9)
print (vector)
```
Check it out.

In [ ]:
import numpy as np
vect = np.linspace(11,31, 15)
vect


array([11.        , 12.42857143, 13.85714286, 15.28571429, 16.71428571,
       18.14285714, 19.57142857, 21.        , 22.42857143, 23.85714286,
       25.28571429, 26.71428571, 28.14285714, 29.57142857, 31.        ])

In [ ]:
import numpy
vect = numpy.arange (9)
print (vect)

[0 1 2 3 4 5 6 7 8]


In [ ]:
import numpy
vect = numpy.arange (0,9,3)
print (vect)

[0 3 6]


**Functions for creating NumPy vectors with zeros or ones:**

There are other features worth mentioning that can be very useful for generating an array from scratch:

- The instruction **`numpy.zeros (num)`** generates a vector of length `num` where all components have the value zero.

- Similarly, the function **`numpy.ones (num)`** generates the length vector `num` and all components of value 1.

The following code generates a 25-component NumPy vector, all of which are initially zero.
```Python
import numpy
x = numpy.zeros (25)
print (x)
```

Run it to see the result.

In [ ]:
import numpy as np
x = np.zeros (5)
print (x)

[0. 0. 0. 0. 0.]


**Exercise:** Following the example in the previous cell, then generate a vector of 10 components, all of them initially equal to 1, and assign it to a variable `y`. Enter the value of `y`:

#### Create a NumPy array by applying a function to an existing NumPy array

_Arrays_ can also be obtained by applying a NumPy function to a pre-existing array.

In the example of the beginning we applied the function `numpy.sin ()` to the array `angles` and its result,` sin_ang`, was of type `numpy.ndarray`.

#### Create a NumPy vector from user-entered data

To create numpy vectors with user-entered data we have different options:

1) Create a list with the data entered by the user one by one and then convert the list to NumPy array.

Here's an example (run it in the following cell):
```Python
import numpy
nel = int (input ("Enter the number of elements in the vector:"))
lvec = [] # we create an empty list
for i in range (in):
     comp = input ("Enter the value of component {}:" .format (i))
     lvec.append (float (comp)) # convert it to real and add it to lvec
vec = numpy.array (lvec) # we create an array from the list
print (old)
```

In [ ]:
import numpy
nel = int (input ("Enter the number of elements in the vector:"))
lvec = [] # we create an empty list
for i in range (nel):
     comp = input ("Enter the value of component {}:" .format (i))
     lvec.append (float (comp)) # convert it to real and add it to lvec
vec = numpy.array (lvec) # we create an array from the list
print (vec)

Enter the number of elements in the vector:6
Enter the value of component 0:-1
Enter the value of component 1:3
Enter the value of component 2:5
Enter the value of component 3:7
Enter the value of component 4:0
Enter the value of component 5:-1
[-1.  3.  5.  7.  0. -1.]


**Note**: We take this opportunity to highlight the possibility of writing a variable value by including `{}` and `format` in the input statement, which is great for indicating which element of the vector is requested to be entered .

2) Create a numpy vector initially filled with zeros (`numpy.zeros ()`) and then assign the values, component by component with the data entered by the user one by one.

Below is the same example as before but reading the values directly as components of the array:
```Python
import numpy
nel = int (input ("Enter the number of elements in the vector:"))
vec = numpy.zeros (nel) # We create the vector with zeros as components
for i in range (nel):
     comp = input ("Enter the value of component {}:" .format (i))
     vec [i] = float (comp) # we convert it to real and assign it to the "i" component of vec
print (vec)
```

In [ ]:
import numpy
nel = int (input ("Enter the number of elements in the vector:"))
vec = numpy.zeros (nel) # We create the vector with zeros as components
for i in range (nel):
     comp = input ("Enter the value of component {}:" .format (i))
     vec [i] = float (comp) # we convert it to real and assign it to the "i" component of vec
print (vec)

Enter the number of elements in the vector:3
Enter the value of component 0:1
Enter the value of component 1:8
Enter the value of component 2:4
[1. 8. 4.]


In this last example we have made use of the indexing of NumPy vectors which, although very similar to that of lists, we have not yet seen and will deal with in a moment.

3) Enter multiple numeric data all on the same line, separate them into a list, and convert the list into a numpy vector with the instruction `numpy.float _ ()`

Check with the following code:
```Python
import numpy
lin = input ("Enter the components of a vector in a line:")
smooth = lin.split () # separates the line considering the targets
vec = numpy.float_ (smooth) # look at the _ back of the numpy float
print ("List: {}". format (smooth))
print ("Vector: {}". format (old))
```

In [ ]:
import numpy
lin = input ("Enter the components of a vector in a line:")
smooth = lin.split () # separates the line considering the targets
vec = numpy.float_ (smooth) # look at the _ back of the numpy float
print ("List: {}". format (smooth))
print ("Vector: {}". format (vec))

Enter the components of a vector in a line:6 1 5.6 1.2 3 8
List: ['6', '1', '5.6', '1.2', '3', '8']
Vector: [6.  1.  5.6 1.2 3.  8. ]


4) Read data from a file. We will see this variant in a future session.

### 9.3.2 Dimensions of a NumPy array

Once we have created a NumPy array we can find out about its **attributes** (properties) using a syntax similar to that of methods (but note that there are no arguments or parentheses):

```python
x.attribute_name
```

where the `attribute_name` changes depending on what we want to know:

- `ndim`: number of dimensions (1 in the case of vectors, 2 for matrices, etc.).
- `shape`: shape of the array, is the number of elements in each dimension (for example number of components in a vector, number of rows and columns in an array).
- `size`: the total number of elements in the array.

Observe the contents of the following code in detail and then run it.
```Python
import numpy
x = numpy.linspace (-1, 1, 21) # We create the vector
n_dim = x.ndim
print ("Number of dimensions: {}". format (n_dim))
n_size = x.size
print ("Number of components obtained with .size: {}". format (n_size))
print ("Number of elements in each dimension obtained with .shape: {}". format (x.shape))
long = len (x)
print ("Number of components obtained with len: {}" .format (long))
```

In [ ]:
import numpy
x = numpy.linspace (-1, 1, 21) # We create the vector
n_dim = x.ndim
print ("Number of dimensions: {}". format (n_dim))
n_size = x.size
print ("Number of components obtained with .size: {}". format (n_size))
print ("Number of elements in each dimension obtained with .shape: {}". format (x.shape))
long = len (x)
print ("Number of components obtained with len: {}" .format (long))

Number of dimensions: 1
Number of components obtained with .size: 21
Number of elements in each dimension obtained with .shape: (21,)
Number of components obtained with len: 21


Note that in the case of a vector the number of components can be obtained with both _.size_ and _len ()_.

### 9.3.3 Indexing

An individual element or subset (_slice_) can be selected from a NumPy array in multiple ways. The case of one-dimensional arrays is very simple, apparently there are no differences with that of Python lists.

#### Individual elements of a NumPy array

To obtain a specific value contained in a NumPy vector **we need to specify the name of the variable and, in brackets, the index** (the position it occupies in the _ndarray_). Attention! It should be borne in mind that, as in the case of lists, the first element occupies the zero position.

In the following example we get the value of the seventh element (value 6 of the index) of the variable `vec`:
```Python
import numpy
vec = numpy.linspace (-1,1,11) # We generate a vector with 11 equally spaced values between -1 and 1
print (old)
print (old [6])
```
Check it out

In [ ]:
import numpy
vec = numpy.linspace (-1,1,11) # We generate a vector with 11 equally spaced values between -1 and 1
print (vec)
print (vec [6])

[-1.  -0.8 -0.6 -0.4 -0.2  0.   0.2  0.4  0.6  0.8  1. ]
0.20000000000000018


#### Slices of NumPy arrays

To obtain a _slice_ (segment or subset) of a NumPy vector (one-dimensional array) we can use the same syntax as in the case of lists.

```python
vec [start:end:step] # "slice" from "vec" position to "end" position with "step" jumps
vec [start:end] # all items from "vec" from "start" to "end-1"
vec [start:] # all elements of "vec" from "start" to FINAL
vec [:end] # all items from "vec" from FIRST to "end-1"
vec [:] # the whole vector
```

Attention! It is very important to note that **if the final slice limit is specified, it is excluded from the result**.

Check this by running this code in the following cell:
```Python
import numpy
vec = numpy.linspace (-1,1,11) # We generate a vector with 11 equally spaced values between -1 and 1
print (vec) # The whole vector
print (see [3: 6]) # Items with index 3, 4, and 5
```

In [ ]:
import numpy
vec = numpy.linspace (-1,1,11) # We generate a vector with 11 equally spaced values between -1 and 1
print (vec) # The whole vector
print (vec [3: 6]) # Items with index 3, 4, and 5

[-1.  -0.8 -0.6 -0.4 -0.2  0.   0.2  0.4  0.6  0.8  1. ]
[-0.4 -0.2  0. ]


#### Assigning values to NumPy vector elements

As with lists, we can modify an element (a component) of the NumPy array by specifying its index and making the corresponding assignment.

Please read this example in detail and run it in the following cell:
```Python
import numpy
vec = numpy.linspace (-1,1,11) # We generate a vector with 11 equally spaced values between -1 and 1
print ("Vector generated by linspace: {}". format (vec))
vec [5] = 11.0
print ("Vector after first assignment: {}". format (vec))
vec [: 3] = [12.0, 13.0, 14.0]
print ("Vector after second assignment: {}". format (vec))
```

In [ ]:
import numpy
vec = numpy.linspace (-1,1,11) # We generate a vector with 11 equally spaced values between -1 and 1
print ("Vector generated by linspace: {}". format (vec))
vec [5] = 11.0
print ("Vector after first assignment: {}". format (vec))
vec [: 3] = [12.0, 13.0, 14.0]
print ("Vector after second assignment: {}". format (vec))

Vector generated by linspace: [-1.  -0.8 -0.6 -0.4 -0.2  0.   0.2  0.4  0.6  0.8  1. ]
Vector after first assignment: [-1.  -0.8 -0.6 -0.4 -0.2 11.   0.2  0.4  0.6  0.8  1. ]
Vector after second assignment: [12.  13.  14.  -0.4 -0.2 11.   0.2  0.4  0.6  0.8  1. ]


#### Copy a numpy array (or slice) to another numpy array

As we saw in the case of the lists, if you have a numpy array _a_ and want to copy to another numpy array _b_ it is not advisable to do

```Python
b = a
```

If this is done, the result of working with a and b may not be as expected (Python considers the vector to be unique and can be accessed with both the name _a_ and the name _b_ so that if n change one, change the other too!). And the same goes for a slice instead of _a_ integer.

If you want to make sure you have a separate copy, you can:

```python
b = a.copy ()
```
or

```python
b = numpy.array (a)
```

## 9.4 Arithmetic operations with NumPy vectors

Operations between two NumPy vectors (and two NumPy arrays in general) are performed **element by element**, the first element of one with the first element of the other, the second of one with the second of l 'other, ...

In the following example we do simple arithmetic operations between two NumPy vectors.
```Python
import numpy
arr1 = numpy.linspace (0,20,5) # A 5-component vector is created
print ("Primer array", arr1)
arr2 = numpy.linspace (20,40,5) # Another 5-component vector
print ("Second array", arr2)
# sum of arrays
dif = arr1 + arr2
print ("Sum:", diff)
# array difference
dif = arr1 - arr2
print ("Difference:", diff)
# array product
prod = arr1 * arr2
print ("Product:", prod)
# quotient of arrays
quo = arr1 / arr2
print ("Quocient:", quo)
```

Observe in detail what it does and run it:

In [ ]:
import numpy
arr1 = numpy.linspace (0,20,5) # A 5-component vector is created
print ("Primer array", arr1)
arr2 = numpy.linspace (20,40,5) # Another 5-component vector
print ("Second array", arr2)
# sum of arrays
dif = arr1 + arr2
print ("Sum:", dif)
# array difference
dif = arr1 - arr2
print ("Difference:", dif)
# array product
prod = arr1 * arr2
print ("Product:", prod)
# quotient of arrays
quo = arr1 / arr2
print ("Quocient:", quo)

Primer array [ 0.  5. 10. 15. 20.]
Second array [20. 25. 30. 35. 40.]
Sum: [20. 30. 40. 50. 60.]
Difference: [-20. -20. -20. -20. -20.]
Product: [  0. 125. 300. 525. 800.]
Quocient: [0.         0.2        0.33333333 0.42857143 0.5       ]


Note that:

- As we have already said, the operations are carried out element by element
- Its result is a NumPy array and has the same dimensions as its operands.

**Caution:** In general, if we do operations between NumPy vectors that do NOT have the same number of elements we will get a runtime error.

**Arithmetic operations can also be performed between a scalar and a vector**. The result is the operation of each element of the vector with the scalar.

Check with the following code:
```Python
import numpy
arr = numpy.linspace (0,20,5)
print (arr)
arr2 = 3 * arr
print (arr2)
```
Run it in the following cell and study the result:

In [ ]:
import numpy
arr = numpy.linspace (0,20,5)
print (arr)
arr2 = 3 * arr
print (arr2)

[ 0.  5. 10. 15. 20.]
[ 0. 15. 30. 45. 60.]



## 9.5 Efficient Array Calculation: Universal Functions

_Universal functions_, known as **ufuncs** are a very prominent element of NumPy. A _ufunc_ is a function that, if applied to a scalar, produces a scalar, but if applied to a NumPy vector, it results in an array of the same size, obtained by applying the function to each of its elements.

The following [link](http://docs.scipy.org/doc/numpy/reference/ufuncs.html) provides a description of all _ufuncs_. Some of the most interesting are:

- Mathematical functions: `log`,` log10`, `exp`, ...
- Trigonometric functions: `body`,` sin`, `tan`, ...


At the beginning of this notebook we actually used a _ufunc_, `numpy.sin ()`, to calculate the sine of an angle array that we got from a list.

Now, in another example, we will do the same with numpy.cos but we will get the angle array beforehand with the `numpy.linspace` function.
```Python
import numpy
angles = numpy.linspace (0, numpy.pi, 5) # Vector of angles (same as in the first example)
print (angles)
cos_ang = numpy.cos (angles) # The cosine of all of them is calculated with a single instruction
print (cos_ang)
```

Run the following cell and observe how it works:

In [ ]:
import numpy
angles = numpy.linspace (0, numpy.pi, 5) # Vector of angles (same as in the first example)
print (angles)
cos_ang = numpy.cos (angles) # The cosine of all of them is calculated with a single instruction
print (cos_ang)

[0.         0.78539816 1.57079633 2.35619449 3.14159265]
[ 1.00000000e+00  7.07106781e-01  6.12323400e-17 -7.07106781e-01
 -1.00000000e+00]


## 9.6 Array Statistics

The NumPy module incorporates a series of functions that allow the statistical analysis of a data collection in an efficient way and using a very compact notation. Specifically, we highlight the functions:

- `numpy.min ()` provides the minimum value of the array
- `numpy.argmin ()` returns the **position** (index) that occupies the minimum value within the array
- `numpy.max ()` provides the maximum value of the array
- `numpy.argmax ()` returns the **position** (index) that occupies the maximum value within the array
- `numpy.mean ()` provides the [arithmetic mean](https://en.wikipedia.org/wiki/Arithmetic_mean) of the array values
- `numpy.var ()` provides the [variance](https://en.wikipedia.org/wiki/Variance) of the array values
- `numpy.std ()` provides the [standard deviation](https://en.wikipedia.org/wiki/Standard_deviation)
- `numpy.sum ()` returns the sum of all values ​​in the array
- `numpy.prod ()` returns the producer of all values ​​in the array

In all these functions the first argument is the name of the variable that contains the NumPy array.

You can see the use of some of these features by running this code in the following cell:
```Python
import numpy
# The following statement is used to generate a vector of 10 random data
# Each time it runs it gives different values
values ​​= numpy.random.random (10) # 10 random values ​​in the range [0,1)
print ("Values: {}". format (values))
val_max = numpy.max (values) # Maximum value of vector components
print ("Maximum value: {}". format (max_value))
pos_max = numpy.argmax (values) # Position of the maximum value in the vector (starting with 0)
print ("Maximum value index: {}". format (pos_max))
val_min = numpy.min (values) # Minimum value of vector components
print ("Minimum value: {}". format (val_min))
pos_min = numpy.argmin (values) # Minimum value position in vector (starting with 0)
print ("Minimum value index: {}". format (pos_min))
```

Try it several times.

In [ ]:
import numpy
# The following statement is used to generate a vector of 10 random data
# Each time it runs it gives different values
values = numpy.random.random (10) # 10 random values ​​in the range [0,1)
print ("Values: {}". format (values))
val_max = numpy.max (values) # Maximum value of vector components
print ("Maximum value: {}". format (val_max))
pos_max = numpy.argmax (values) # Position of the maximum value in the vector (starting with 0)
print ("Maximum value index: {}". format (pos_max))
val_min = numpy.min (values) # Minimum value of vector components
print ("Minimum value: {}". format (val_min))
pos_min = numpy.argmin (values) # Minimum value position in vector (starting with 0)
print ("Minimum value index: {}". format (pos_min))

Values: [0.61456012 0.01615299 0.55466334 0.39362083 0.34181736 0.30084242
 0.73275871 0.72513693 0.50013746 0.80286394]
Maximum value: 0.8028639377239485
Maximum value index: 9
Minimum value: 0.016152987682307773
Minimum value index: 1


## 9.7. NumPy : Matrices


An array is a two-dimensional array like this:


$$
\left ( \begin{array}{cccc}
3 & 4 & 7 & 8 \\ 6 & 1 & 0 & 3 \\ 11 & 9 & 7 & 5
\end{array} \right )
$$

where you have an array of 3 rows and 4 columns (we also say it is a 3x4 array).

### 9.7.1 Creating arrays from NumPy functions


- The function `numpy.zeros (nfil, ncol))` generates an array (two-dimensional array) where all components have the value zero (real). _nfil_ indicates the number of rows and _ncol_ the number of columns.

- The `numpy.ones (nfil, ncol))` function does the same thing but with all components with the value 1 (real).

Note that there is **a double parenthesis game**, which was not necessary in the case of a vector.

For example, the following instructions generate a 3x4 array where all elements are zero and a 5x4 array where all elements are ones:
```Python
import numpy
mat_A = numpy.zeros((3,4))
print ("Matrice A")
print(mat_A)
mat_B = numpy.ones((5,4))
print ("Matrice B")
print(mat_B)
```
Check it in the following cell:

In [ ]:
import numpy
mat_A = numpy.zeros((3,4))
print ("Matrice A")
print(mat_A)
mat_B = numpy.ones((5,4))
print ("Matrice B")
print(mat_B)

Matrice A
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Matrice B
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### 9.7.2 Create arrays from user-entered data

We have seen before that to create _arrays_ with data entered by the user we have different options:

1. Create a list as we read the data and then convert the list to NumPy array.
2. Create an array full of zeros (`numpy.zeros`) or ones (` numpy.ones`) and then assign the values, component by component.
3. Read the data in a file. We will see this variant in another session.

Let's look at an example of the second option where we build a 4x3 array from data entered by the user.

```Python
import numpy
mat = numpy.zeros((4,3))   # We create the matrice 4x3, all zeros

for i in range(4):         # Cycle over the rows of the matrix
    for j in range(3):     # Cycle over the columns of the matrix
        mat[i,j] = float(input("Introduce the value of the element {},{}: ".format(i,j)))   # Enter the value

print(mat)
```
Run it to see how it works:

In [ ]:
import numpy
mat = numpy.zeros((4,3))   # We create the matrice 4x3, all zeros

for i in range(4):         # Cycle over the rows of the matrix
    for j in range(3):     # Cycle over the columns of the matrix
        mat[i,j] = float(input("Introduce the value of the element {},{}: ".format(i,j)))   # Enter the value

print(mat)

Introduce the value of the element 0,0: 3
Introduce the value of the element 0,1: 2
Introduce the value of the element 0,2: 1
Introduce the value of the element 1,0: 0
Introduce the value of the element 1,1: 1
Introduce the value of the element 1,2: 4
Introduce the value of the element 2,0: 6
Introduce the value of the element 2,1: -8
Introduce the value of the element 2,2: 5
Introduce the value of the element 3,0: 0
Introduce the value of the element 3,1: 3
Introduce the value of the element 3,2: 1
[[ 3.  2.  1.]
 [ 0.  1.  4.]
 [ 6. -8.  5.]
 [ 0.  3.  1.]]


In [ ]:
import numpy as np
mat_a = np.zeros((2,2))   # We create the matrice 2x2, all zeros
for i in range(2):         # Cycle over the rows of the matrix
    for j in range(2):     # Cycle over the columns of the matrix
        mat_a[i,j] = float(input("Introduce the value of the element {},{}: ".format(i,j)))   # Enter the value
print(mat_a)

mat_b = np.zeros((2,2))   # We create the matrice 2x2, all zeros
for i in range(2):         # Cycle over the rows of the matrix
    for j in range(2):     # Cycle over the columns of the matrix
        mat_b[i,j] = float(input("Introduce the value of the element {},{}: ".format(i,j)))   # Enter the value
print(mat_b)

mat_c = np.zeros((2,2))   # We create the matrice 2x2, all zeros
for i in range(2):         # Cycle over the rows of the matrix
    for j in range(2):     # Cycle over the columns of the matrix
        mat_c[i,j] = float(input("Introduce the value of the element {},{}: ".format(i,j)))   # Enter the value
print(mat_c)

mat_a_inv = np.linalg.inv(mat_a)
print(mat_a_inv)
mat_b_inv = np.linalg.inv(mat_b)
print(mat_b_inv)

x = np.matmul(mat_a_inv,mat_c)
ans = np.matmul(mat_c,x)
print(ans)

Introduce the value of the element 0,0: 1
Introduce the value of the element 0,1: 1
Introduce the value of the element 1,0: 1
Introduce the value of the element 1,1: 2
[[1. 1.]
 [1. 2.]]
Introduce the value of the element 0,0: 4
Introduce the value of the element 0,1: 1
Introduce the value of the element 1,0: 3
Introduce the value of the element 1,1: 1
[[4. 1.]
 [3. 1.]]
Introduce the value of the element 0,0: 24
Introduce the value of the element 0,1: 7
Introduce the value of the element 1,0: 31
Introduce the value of the element 1,1: 9
[[24.  7.]
 [31.  9.]]
[[ 2. -1.]
 [-1.  1.]]
[[ 1. -1.]
 [-3.  4.]]
[[457. 134.]
 [590. 173.]]


 ***